[package]
name = "boid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
glow = "0.10.0"
imgui-glow-renderer = "0.8.3"
imgui-winit-support = "0.8.2"
imgui = "0.8.2"
glutin = "0.27.0"
rand = "0.8.4" 
